/*
 * ⚠️ AI-GENERATED CODE ⚠️
 *
 * This code was generated by AI (Augment Agent) for educational purposes.
 *
 * INTENTIONALLY VULNERABLE CODE - FOR EDUCATIONAL PURPOSES ONLY
 *
 * This file contains examples of common security vulnerabilities:
 * 1. Cross-Site Scripting (XSS)
 * 2. SQL Injection
 * 3. Null Dereference
 * 4. OS Command Injection
 * 5. Code Injection (eval)
 * 6. Path Traversal
 * 7. Server-Side Request Forgery (SSRF)
 * 8. Open Redirect
 * 9. Weak Password Hashing (MD5)
 *
 * DO NOT USE IN PRODUCTION
 */

const express = require('express');
const sqlite3 = require('sqlite3').verbose();
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const http = require('http');
const crypto = require('crypto');
const app = express();
const port = 3000;

// Middleware
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Initialize SQLite database
const db = new sqlite3.Database(':memory:');

// Create a sample users table
db.serialize(() => {
  db.run("CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, password TEXT, email TEXT)");
  db.run("INSERT INTO users (username, password, email) VALUES ('admin', 'admin123', 'admin@example.com')");
  db.run("INSERT INTO users (username, password, email) VALUES ('user1', 'pass123', 'user1@example.com')");
});

/* ==============================
   VULNERABILITY 1: Cross-Site Scripting (XSS)
   ============================== */

// Reflected XSS - User input is directly rendered in HTML without sanitization
app.get('/search', (req, res) => {
  const searchTerm = req.query.q;

  // VULNERABLE: Directly embedding user input into HTML
  res.send(`
    <html>
      <head><title>Search Results</title></head>
      <body>
        <h1>Search Results</h1>
        <p>You searched for: ${searchTerm}</p>
        <p>No results found.</p>
      </body>
    </html>
  `);
});

// Stored XSS - User input stored and rendered without sanitization
const comments = [];

app.post('/comment', (req, res) => {
  const comment = req.body.comment;
  const username = req.body.username;

  // VULNERABLE: Storing unsanitized user input
  comments.push({ username, comment, timestamp: new Date() });

  res.json({ success: true, message: 'Comment added' });
});

app.get('/comments', (req, res) => {
  // VULNERABLE: Rendering stored user input without sanitization
  let html = '<html><head><title>Comments</title></head><body><h1>Comments</h1>';

  comments.forEach(c => {
    html += `<div class="comment">
      <strong>${c.username}</strong> said: ${c.comment}
      <br><small>${c.timestamp}</small>
    </div><hr>`;
  });

  html += '</body></html>';
  res.send(html);
});

/* ==============================
   VULNERABILITY 2: SQL Injection
   ============================== */

// SQL Injection in login endpoint
app.post('/login', (req, res) => {
  const username = req.body.username;
  const password = req.body.password;

  // VULNERABLE: String concatenation in SQL query
  const query = `SELECT * FROM users WHERE username = '${username}' AND password = '${password}'`;

  console.log('Executing query:', query);

  db.get(query, (err, row) => {
    if (err) {
      res.status(500).json({ error: err.message });
      return;
    }

    if (row) {
      res.json({ success: true, message: 'Login successful', user: row });
    } else {
      res.json({ success: false, message: 'Invalid credentials' });
    }
  });
});

// SQL Injection in user search
app.get('/users/search', (req, res) => {
  const searchTerm = req.query.term;

  // VULNERABLE: Direct string interpolation in SQL
  const query = `SELECT id, username, email FROM users WHERE username LIKE '%${searchTerm}%'`;

  console.log('Executing query:', query);

  db.all(query, (err, rows) => {
    if (err) {
      res.status(500).json({ error: err.message });
      return;
    }
    res.json({ users: rows });
  });
});

/* ==============================
   VULNERABILITY 3: Null Dereference
   ============================== */

// Null dereference when accessing user profile
app.get('/profile/:userId', (req, res) => {
  const userId = req.params.userId;

  db.get('SELECT * FROM users WHERE id = ?', [userId], (err, user) => {
    if (err) {
      res.status(500).json({ error: err.message });
      return;
    }

    // VULNERABLE: No null check - will crash if user is undefined
    // This will throw "Cannot read property 'username' of undefined"
    const profileHtml = `
      <html>
        <body>
          <h1>Profile: ${user.username}</h1>
          <p>Email: ${user.email}</p>
          <p>User ID: ${user.id}</p>
        </body>
      </html>
    `;

    res.send(profileHtml);
  });
});

// Another null dereference example
app.post('/update-settings', (req, res) => {
  const settings = req.body.settings;

  // VULNERABLE: No validation that settings exists or has required properties
  // Will crash if settings is null/undefined or missing properties
  const theme = settings.theme.toUpperCase();
  const notifications = settings.notifications.email.enabled;

  res.json({
    success: true,
    theme: theme,
    emailNotifications: notifications
  });
});

/* ==============================
   VULNERABILITY 4: OS Command Injection
   ============================== */

// VULNERABLE: User input concatenated into a shell command
app.get('/ping', (req, res) => {
  const host = req.query.host;
  exec('ping -c 1 ' + host, (err, stdout, stderr) => {
    res.send(`<pre>${stdout}${stderr}</pre>`);
  });
});

/* ==============================
   VULNERABILITY 5: Code Injection
   ============================== */

// VULNERABLE: User input evaluated as JavaScript
app.post('/calculate', (req, res) => {
  const expression = req.body.expression;
  const result = eval(expression);
  res.json({ result: result });
});

// VULNERABLE: User input compiled into a function
app.post('/transform', (req, res) => {
  const transform = new Function('value', req.body.code);
  res.json({ result: transform(req.body.value) });
});

/* ==============================
   VULNERABILITY 6: Path Traversal
   ============================== */

// VULNERABLE: User-controlled file path read from disk (e.g. ?file=../../etc/passwd)
app.get('/download', (req, res) => {
  const filePath = path.join(__dirname, 'uploads', req.query.file);
  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.status(404).send('Not found');
      return;
    }
    res.send(data);
  });
});

/* ==============================
   VULNERABILITY 7: Server-Side Request Forgery (SSRF)
   ============================== */

// VULNERABLE: Server fetches an arbitrary user-supplied URL
app.get('/fetch', (req, res) => {
  http.get(req.query.url, (response) => {
    response.pipe(res);
  });
});

/* ==============================
   VULNERABILITY 8: Open Redirect
   ============================== */

// VULNERABLE: Redirects to an unvalidated user-supplied URL
app.get('/redirect', (req, res) => {
  res.redirect(req.query.next);
});

/* ==============================
   VULNERABILITY 9: Weak Password Hashing
   ============================== */

// VULNERABLE: Unsalted MD5 used to hash passwords
app.post('/register', (req, res) => {
  const hash = crypto.createHash('md5').update(req.body.password).digest('hex');
  db.run(`INSERT INTO users (username, password, email) VALUES ('${req.body.username}', '${hash}', '${req.body.email}')`);
  res.json({ success: true });
});

app.listen(port, () => {
  console.log(`Vulnerable server running at http://localhost:${port}`);
  console.log('\nWARNING: This server contains intentional security vulnerabilities!');
  console.log('For educational purposes only - DO NOT use in production!\n');
});
